import type { Metadata } from "next";
import "../styles/globals.css";
import { cn } from "@/lib/utils";
import "@fontsource/metropolis/300.css";
import "@fontsource/metropolis/400.css";
import "@fontsource/metropolis/500.css";
import "@fontsource/metropolis/600.css";
import "@fontsource/metropolis/700.css";
import "@fontsource/metropolis/800.css";

export const metadata: Metadata = {
  title: "Tanizstretto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main
          className={cn("min-h-screen bg-background font-sans antialiased")}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
