name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

# build_and_push:
#     name: Build image & push
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true
          buildArgs: |
            PUBLIC_HELLO=world
      # Deploy the Docker image to the CapRover instance
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:
          server: ${{ secrets.CAPROVER_SERVER }} # CapRover server URL
          app: ${{ secrets.APP_NAME }} # CapRover app name
          token: '${{ secrets.APP_TOKEN }}' # CapRover app token
          image: ${{ steps.meta.outputs.tags }} # Docker image to deploy
