name: build + publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

# build_and_push:
#     name: Build image & push
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          secrets: |
            "PUBLIC_SANITY_PROJECT_ID=${{ secrets.PUBLIC_SANITY_PROJECT_ID }}"
            "PUBLIC_SANITY_DATASET=${{ secrets.PUBLIC_SANITY_DATASET }}"
            "PUBLIC_BASE_URL=${{ secrets.PUBLIC_BASE_URL }}"
            "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
            "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
            "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}"
            "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          accessToken: ${{ github.token }}
          containerRegistry: true
          buildArgs: |
            PUBLIC_HELLO=world
      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://tanzistretto.com
          app: 'storefront'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/reasat-rafio/tanzistretto-storefront:latest'
